export const START_STOPWATCH = 'START_STOPWATCH';
export const SET_TOTAL_TIME = 'SET_TOTAL_TIME';
export const RESET_STOPWATCH = 'RESET_STOPWATCH';
export const STOP_STOPWATCH = 'STOP_STOPWATCH';
export const SET_LAP = 'SET_LAP';